stages:
  - name: Build image
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: harshadadeokar/sample-api
          pushRemote: true
          registry: hub.docker.com

  - name: Deploy
    steps:
      - applyYamlConfig:
          path: ./kubernetes.yaml
